### PR TITLE
fix(terraform parser): remove resource reference in dependent policies

### LINKED ISSUE #5489: S3 Bucket Policy Accepts HTTP Requests False Positive
I am unable to pass my KICS scan.  I fail with this result (note I have removed some sensitive info from this output):

```
                   .0MO.                                    
                   OMMMx                                    
                   ;NMX;                                    
                    ...           ...              ....     
WMMMd     cWMMM0.  KMMMO      ;xKWMMMMNOc.     ,xXMMMMMWXkc.
WMMMd   .0MMMN:    KMMMO    :XMMMMMMMMMMMWl   xMMMMMWMMMMMMl
WMMMd  lWMMMO.     KMMMO   xMMMMKc...'lXMk   ,MMMMx   .;dXx 
WMMMd.0MMMX;       KMMMO  cMMMMd        '    'MMMMNl'       
WMMMNWMMMMl        KMMMO  0MMMN               oMMMMMMMXkl.  
WMMMMMMMMMMo       KMMMO  0MMMX                .ckKWMMMMMM0.
WMMMMWokMMMMk      KMMMO  oMMMMc              .     .:OMMMM0
WMMMK.  dMMMM0.    KMMMO   KMMMMx'    ,kNc   :WOc.    .NMMMX
WMMMd    cWMMMX.   KMMMO    kMMMMMWXNMMMMMd .WMMMMWKO0NMMMMl
WMMMd     ,NMMMN,  KMMMO     'xNMMMMMMMNx,   .l0WMMMMMMMWk, 
xkkk:      ,kkkkx  okkkl        ;xKXKx;          ;dOKKkc    
Scanning with Keeping Infrastructure as Code Secure v1.5.10
Files scanned: 26
Parsed files: 26
Queries loaded: 48
Queries failed to execute: 0
------------------------------------
Description: S3 Bucket policy should not accept HTTP Requests
Platform: Terraform
	[2]: terraform/s3.tf:159
		158:   bucket = aws_s3_bucket.common.id
		159:   policy = data.aws_iam_policy_document.common_policy.json
		160: }
Results Summary:
HIGH: 0
MEDIUM: 1
LOW: 0
INFO: 0
TOTAL: 1
Results saved to file kics-scan-report.json
Scan duration: 9.29071451s
*********************************
         🕵️ FINDINGS            
*********************************
🚨 MEDIUM (1):
	[4bc4dd4c-7d8d-405e-a0fb-57fa4c31b4d9] S3 Bucket Policy Accepts HTTP Requests
[FAILURE] 🚨 CIS MEDIUM or higher findings found.
```

Here's the relevant Terraform...

```hcl

resource "aws_s3_bucket" "common" {
  bucket        = "name" # 63 char limit
  acl           = "private"
  force_destroy = true
}

resource "aws_s3_bucket_policy" "https_common" {
  bucket = aws_s3_bucket.common.id
  policy = data.aws_iam_policy_document.common_policy.json
}

data "aws_iam_policy_document" "common_policy" {
  statement {
    sid    = "https"
    effect = "Deny"
    principals {
      type        = "*"
      identifiers = ["*"]
    }
    actions = [
      "s3:*"
    ]
    resources = [
      aws_s3_bucket.common.arn,
      "${aws_s3_bucket.common.arn}/*"
    ]
    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values = [
        "false"
      ]
    }
  }
}
```

### Expected Behavior
I expect to _not_ find the MEDIUM vulnerability.

### Actual Behavior
I do find the MEDIUM vulnerability.

-  Version: 1.5.10
-  Platform: Terraform
-  Sub-Platform: AWS

I've followed the advice in [aws docs](https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-policy-for-config-rule/).  But, perhaps I am not translating it to Terraform correctly.  Or, maybe there is still an issue with the [query](https://github.com/Checkmarx/kics/blob/v1.5.10/assets/queries/terraform/aws/s3_bucket_policy_accepts_http_requests/query.rego).

Thanks in advance for any help you can provide.

### PR DESCRIPTION
**Pull request by cxMiguelSilva**
Closes #5489

**Proposed Changes**
- remove referenced resources in policies on `pkg/parser/terraform/data_source.go`

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

File: pkg/parser/terraform/data_source.go [hunk 1]
```diff
@@ -290,3 +292,11 @@ func parseDataSourceBody(body *hclsyntax.Body) string {
 	}
 	return buffer.String()
 }
+
+func deleteResourcesFromPolicy(body *hclsyntax.Body) {
```
Comment (rafaela-soares) [inline pkg/parser/terraform/data_source.go:296]: I think that is not a "good idea" to delete `resources` from policy because of future queries that will need to look at this field.

KICS already have some queries that look to `Resource`. It something that we should look carefully. As examples:
- kics\assets\queries\terraform\aws\iam_role_with_full_privileges
- kics\assets\queries\terraform\aws\iam_role_policy_passrole_allows_all
- kics\assets\queries\terraform\aws\iam_policy_grants_full_permissions

**Review by rafaela-soares — CHANGES_REQUESTED** [review]

**Review by rafaela-soares — APPROVED** [review]
LGTM 🚀
