### PR TITLE
Fix bugs with tracker counters

### LINKED ISSUE #2735: Incorrect Files scanned and Parsed files counters for Helm and Docker
### Expected Behavior

Incorrect counters for Files scanned and Parsed 

### Actual Behavior

Correct counters for Files scanned and Parsed

### PR DESCRIPTION
**Pull request by joaoReigota1**
Closes #2735 

**Proposed Changes**
- Fixed Bug where tracker counters weren't correct
- Fixed Issue where subcharts in helm would be re-rendered
- Resolved files under general resolver are now added to the excluded files
- Added new function to FileSystemSourceProvider to add new excluded files 
- Added/Improved Unit tests for pkg/engine/provider
- Refactored helm part of get sources

I submit this contribution under Apache-2.0 license.

### CODE REVIEW

File: pkg/engine/provider/filesystem.go [hunk 1]
```diff
@@ -146,6 +162,9 @@ func (s *FileSystemSourceProvider) checkConditions(info os.FileInfo, extensions
 		if err != nil {
```
Comment (felipe-avelar) [inline pkg/engine/provider/filesystem.go:162]: I think this could be `err != nil || resolved` instead two ifs

File: pkg/engine/provider/provider.go [hunk 2]
```diff
@@ -12,13 +12,13 @@ import (
...
+type ResolverSink func(ctx context.Context, filename string) ([]string, error)
 
 // SourceProvider is the interface that wraps the basic GetSources method.
 // GetBasePath returns base path of FileSystemSourceProvider
 // GetSources receives context, receive ID, extensions supported and a sink function to save sources
 type SourceProvider interface {
 	GetBasePath() string
 	GetSources(ctx context.Context, extensions model.Extensions, sink Sink, resolverSink ResolverSink) error
-	checkConditions(info os.FileInfo, extensions model.Extensions, path string) (bool, error)
+	checkConditions(info os.FileInfo, extensions model.Extensions, path string, resolved bool) (bool, error)
```
Comment (felipe-avelar) [inline pkg/engine/provider/provider.go:23]: Couldn't this be removed from interface definition? Since it is a private function I don't see any reason to this be part of interface definition...

**Review by felipe-avelar — CHANGES_REQUESTED** [review]
Please check comments

File: pkg/engine/provider/provider.go (hunk 2 above)
Comment (rogeriopeixotocx) [reply pkg/engine/provider/provider.go:23]: I agree with removing this private function from the interface.

**Review by rogeriopeixotocx — CHANGES_REQUESTED** [review]
Besides removing the private function from the interface I believe it looks good

**Review by rogeriopeixotocx — APPROVED** [review]
LGTM
