### PR TITLE
fix: deleted extraction folder after KICS scan

### LINKED ISSUE #4585: kics-extract folder created during the kics scan is not removed and cause disk quota exceeded issue in Docker container
kics-extract folder created during the kics scan is not removed. I am running the kics (Command line) against our gitlab source repository in docker a container where multiple scans are executed simultaneously and each scan is creating a kics-extract folder to store downloaded gitlab source code in /tmp (by default linux temporary directory) but those folders and source code is not removed after the scan is completed. 

./kics_1.4.5/kics -s scan --no-progress --minimal-ui -q <query path> -p <git URL> -o --output-name
### Expected Behavior

kics should remove the extract folder once the scan is completed.

### Actual Behavior

I am seeing a lot of kics-extract folders under /tmp folder which cause disk quota exceeded problem and impacts subsequent scans  

### Steps to Reproduce the Problem

1.  step  - Run KICS as command line in a Docker container to scan multiple gitlab source code repository simultaneously
2.  step 2 - 
3.  step 3

### Specifications
(N/A if not applicable)

-   Version: 1.4.7
-   Platform: Linux RHEL 7.6
-   Subsystem:

### PR DESCRIPTION
**Pull request by rafaela-soares**
Closes #4585

**Proposed Changes**
- Deleted extraction folder after KICS scan

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

File: pkg/scan/path_utils.go [hunk 1]
```diff
@@ -124,3 +126,9 @@ func logLoadingQueriesType(types []string) {
 
 	log.Info().Msgf("Loading queries of type: %s", strings.Join(types, ", "))
 }
+
+func deleteExtractionFolder(extractionMap map[string]model.ExtractedPathObject) {
+	for extractionFile := range extractionMap {
+		os.Remove(extractionFile)
```
Comment (joaoReigota1) [inline pkg/scan/path_utils.go:132]: add error check to os.Remove()

**Review by joaoReigota1 — CHANGES_REQUESTED** [review]
Please see Comments

**Review by joaoReigota1 — APPROVED** [review]
LGTM
