### PR TITLE
fix(masked_secrets): Mask Secrets in All Vulnerability Preview

### LINKED ISSUE #5850: Masked Secrets - it works but...
The Secrets are now masked in the HTML report 🎉🎉🎉  but in the report you display : 
- the line before
- the concerned line
- the line after

If the lines before and after are some clear secrets, these secrets are displayed !

image

### PR DESCRIPTION
**Pull request by cxMiguelSilva**
Closes #5850

**Proposed Changes**
- Mask Secrets in All Vulnerability Preview

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

File: pkg/kics/service.go [hunk 1]
```diff
@@ -219,3 +222,21 @@ func prepareScanDocumentValue(bodyType map[string]interface{}, kind model.FileKi
 		}
 	}
 }
+
+func updateMaskedSecrets(vulnerabilities *[]model.Vulnerability, maskedSecretsTracked []secrets.SecretTracker) {
+	for idx, _ := range *vulnerabilities {
+		for _, secretT := range maskedSecretsTracked {
+			if (*vulnerabilities)[idx].FileName == secretT.ResolvedFilePath {
+				vulnLines := (*(*vulnerabilities)[idx].VulnLines)
```
Comment (rafaela-soares) [inline pkg/kics/service.go:230]: We should be careful with the `vulnLines` length. The default is 3 but could be more

**Review by rafaela-soares — CHANGES_REQUESTED** [review]

**Review by rafaela-soares — APPROVED** [review]
LGTM 🚀

**Review by rafaela-soares — APPROVED** [review]
