### PR TITLE
fix(cpu): fix number cpus macos

### LINKED ISSUE #5364: Getting CPU info fails on macOS Docker
Found a bug? You're welcome to [GitHub Discussions](https://github.com/Checkmarx/kics/discussions)

- **Please make sure to:**
  - Describe in details what the problem is
  - Attach a log file with relevant data preferably in DEBUG level (`--log-level=DEBUG`)
  - Attach the scanned sample files, anonymize the data if the original file cannot be provided
  - When attaching files to the issue make sure they are properly formatted

### Expected Behavior

(Which results are expected from KICS?)

No error on getting CPU info.

### Actual Behavior

(Formatted logs and samples helps us to better understand the issue)

```
Scanning with Keeping Infrastructure as Code Secure v1.5.8


9:01PM INF Scanning with Keeping Infrastructure as Code Secure v1.5.8
9:01PM INF Operating system: linux
9:01PM INF Total memory: 3.8G
9:01PM ERR failed to get CPU error="open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory"
```

### Steps to Reproduce the Problem

(Command line arguments and flags used)

1.  `docker run -it -w /path -v $PWD:/path checkmarx/kics:v1.5.8 scan -p /path -v`

### Specifications
(N/A if not applicable)

-   Version: 1.5.8
-   Platform: macOS 12.4
-   Subsystem: Docker Desktop 4.7.0 (77141)

Related to #5321

### PR DESCRIPTION
**Pull request by joaorufi**
Signed-off-by: joaorufi <joao.rufino@checkmarx.com>

Closes #5364

**Proposed Changes**
- Look at `/sys/fs/cgroup/cpu.max` file if `/sys/fs/cgroup/cpu/cpu.cfs_quota_us` file does not exists

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Comment by rafaela-soares** [comment]
@joaorufi, please, take a look at the two extra SAST vulnerabilities

File: internal/console/pre_scan.go [hunk 1]
```diff
@@ -148,12 +148,8 @@ func (console *console) preScan() {
...
 	}
 
-	cpu, err := consoleHelpers.GetNumCPU()
-	if err != nil {
-		log.Err(err).Msg("failed to get CPU")
-	} else {
-		log.Info().Msgf("CPU: %.1f", cpu)
-	}
+	cpu := consoleHelpers.GetNumCPU()
+	log.Info().Msgf("CPU: %.1f", cpu)
```
Comment (rafaela-soares) [inline internal/console/pre_scan.go:152]: Should we print the CPU even if it is set to -1?

**Review by rafaela-soares — CHANGES_REQUESTED** [review]

File: internal/console/pre_scan.go (hunk 1 above)
Comment (joaorufi) [reply internal/console/pre_scan.go:152]: It will never happen that the value is -1. When I return -1 on the function, it also return an error and if there is an error, it tries to get the cpus number in other ways until the last case, returning `float32(runtime.NumCPU())`. This will never be -1
